[server]
headless = true
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true
enableStaticServing = false
address = "localhost"
port = 8501

[runner]
magicEnabled = false

[theme]
base = "dark"
backgroundColor = "#14170F"
secondaryBackgroundColor = "#1B1F14"
primaryColor = "#7A8B5C"
textColor = "#EDEAE0"
font = "sans serif"